services:
  postgres-test:
    image: postgres:latest
    container_name: nestjs-blog-postgres-test
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog_test
    ports:
      - '5433:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  redis-test:
    image: redis:latest
    container_name: nestjs-blog-redis-test
    restart: unless-stopped
    ports:
      - '6380:6379'
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_test_data:/data

volumes:
  postgres_test_data:
  redis_test_data: 